### ISSUE TITLE
Example scene

### ISSUE THREAD

**Issue by ishlilith** [michaelday008/AnyRPGAlphaCode#1]
This project needs an example scene to see how it all works. Even if it's just capsules and cubes instead of real models.

**Comment by michaelday008** [comment]
Thanks for the feedback.  I'm working on one right now.

You can see the current progress by watching the development Livestreams.

I hope to have it done this week sometime.

**Comment by michaelday008** [comment]
Unity package will full set of example scenes is now available at the AnyRPG downloads page : https://www.anyrpg.org/downloads/
